### ISSUE TITLE
6.0.2 Server decleration issue

### ISSUE THREAD

**Issue by mckinney-bryan** [dotnet/WatsonWebserver#124]
Hey all, 

I am following the examples listed on the main code page and whenever I am trying to declare server I keep getting errors. Can someone please assist me on what i'm doing wrong. 

--Thanks!

![image](https://github.com/dotnet/WatsonWebserver/assets/6098858/762ac2e6-7998-471c-a508-ef4cb6aae641)

**Comment by jchristn** [comment]
Hi @mckinney-bryan the class name changed to ```Webserver```
