### ISSUE TITLE
Add URL encoding support and index.html automatic mapping support in ContentRouteHandler

### ISSUE THREAD

**Issue by ChZhongPengCheng33** [dotnet/WatsonWebserver#127]
Add the following code after [here](https://github.com/dotnet/WatsonWebserver/blob/8d129b63811bf900ea63d2f153017541fc487fea/src/WatsonWebserver.Core/ContentRouteManager.cs#L277C7-L277C7):

```c#
if (filePath.EndsWith("/"))
{
    filePath += "index.html";
}
filePath = WebUtility.UrlDecode(filePath);
```
After adding the above code, my Vitespress documentation website can now function properly.

**Comment by jchristn** [comment]
Resolved in v6.1.5, thanks @ChZhongPengCheng33
