### ISSUE TITLE
Watson.Lite : Partial Range Requests status labeled as Internal Server Error 500 despite being handled fine.

### ISSUE THREAD

**Issue by GitHubProUser67** [dotnet/WatsonWebserver#135]
In Watson.Lite, due to it's reliance on an external TCP service, allows for partial range request handling via some customised code.

However, said code, despite working fine, for some reasons print error 500 in the console logs:

![image](https://github.com/dotnet/WatsonWebserver/assets/127040195/0a04a311-4ba9-4de0-a86b-3e14d408d950)

![image](https://github.com/dotnet/WatsonWebserver/assets/127040195/bcd063ae-60e5-410f-8b83-c1b9cad8ef73)

Here is the demonstration of a movie streaming system in https using Watson.Lite, as you can see, works perfect, despite status 500 in the console.

Note, due to the non-lite version relying on httpListener, it is impossible to handle range request on this backend, it could be neat to indicate this in the documentation if someone wanna use it is a backend project.

**Comment by GitHubProUser67** [comment]
After more testing, it can happen sometimes that it does print 206: 

![image](https://github.com/dotnet/WatsonWebserver/assets/127040195/24788d0a-f446-476f-9513-f674025a745d)

My theory is that when this logger only keep tracks of finished requests, effectively sending an internal server error on a dead connection, but a range request can massively bound the interface.

**Comment by jchristn** [comment]
Please share the code you have for your default request handler - seems that is where this content is being served from, correct?

**Comment by jchristn** [comment]
Also - range requests should 100% be supported.  You would have to parse the header `NameValueCollection` to get access to the `Range` header and handle it manually.  Content routes do not support it today, though.

**Comment by GitHubProUser67** [comment]
Here is the code : https://github.com/GitHubProUser67/MultiServer2/blob/main/HTTPSecureServerLite/LocalFileStreamHelper.cs

So what happens is that, the handling of the range is done outside of the API itself, rather I use the API as a transmiter.

**Comment by jchristn** [comment]
Forgot to close this, thanks again!
