### ISSUE TITLE
README/Documentation update

### ISSUE THREAD

**Issue by glloydNAT** [dotnet/WatsonWebserver#142]
It looks like the examples in the README are outdated.  In particular, the Server class has been renamed, has it not, to Webserver?  
It appears that the method signature has also changed? If so and as such, the examples are no longer as useful as they once were.  

Any plans to update the documentation to reflect these (and other) changes?

Thank you

**Comment by jchristn** [comment]
Thanks @glloydNAT I just posted an update, please let me know if I missed anything in particular.  Much appreciated!
